[phases.setup]
cmds = [
    "python -m venv --clear /tmp/venv",  # Changed path to /tmp
    ". /tmp/venv/bin/activate && pip install -r requirements.txt"
]

[phases.install]
cmds = [
    "ln -sf /tmp/venv /opt/venv"  # Symlink to expected location
]